In [1]:
include("../lib/Lib.jl")
include("../lib/DeepSpace.jl")

Main.DeepSpace

In [2]:
using DataFrames, DataFramesMeta
using CSV
using Statistics

In [3]:
KEY = "2019chs_wk1"
YEAR = "2019"
COLUMN = :teleopSwitchOwnershipSec

:teleopSwitchOwnershipSec

In [4]:
(headers, scores, teams) = Lib.read_stacked(KEY, YEAR)
scores[:color] = repeat(["r", "b"], size(scores,1) >> 1)
teams[:color] = repeat(["r", "b"], size(teams,1) >> 1)

360-element Array{String,1}:
 "r"
 "b"
 "r"
 "b"
 "r"
 "b"
 "r"
 "b"
 "r"
 "b"
 "r"
 "b"
 "r"
 ⋮  
 "r"
 "b"
 "r"
 "b"
 "r"
 "b"
 "r"
 "b"
 "r"
 "b"
 "r"
 "b"

In [5]:
DeepSpace.calculated_columns!(scores)
scores[:ownPoints] = scores.totalPoints .- scores.foulPoints .- (3 .* scores.foulCount) .- (9 * scores.techFoulCount)

360-element Array{Int64,1}:
  62
  82
  72
  71
  66
  65
  52
  54
  62
  35
  59
 -25
  63
   ⋮
  20
  12
  70
  45
  59
  47
  57
  60
  74
  66
  51
  55

In [6]:
scores_red = @linq scores |> where(:color .== "r")
scores_blue = @linq scores |> where(:color .== "b")
teams_red = @linq teams |> where(:color .== "r") |> select(:team1, :team2, :team3, :key)
teams_blue = @linq teams |> where(:color .== "b") |> select(:team1, :team2, :team3, :key)

180×4 DataFrame
│ Row │ team1   │ team2   │ team3   │ key                  │
│     │ String⍰ │ String⍰ │ String⍰ │ String⍰              │
├─────┼─────────┼─────────┼─────────┼──────────────────────┤
│ 1   │ frc1418 │ frc614  │ frc6543 │ 2019vahay_f1m1_blue  │
│ 2   │ frc1418 │ frc614  │ frc6543 │ 2019vahay_f1m2_blue  │
│ 3   │ frc1418 │ frc614  │ frc6543 │ 2019vahay_f1m3_blue  │
│ 4   │ frc2988 │ frc116  │ frc611  │ 2019vahay_qf1m1_blue │
│ 5   │ frc2988 │ frc116  │ frc611  │ 2019vahay_qf1m2_blue │
│ 6   │ frc2988 │ frc116  │ frc611  │ 2019vahay_qf1m3_blue │
│ 7   │ frc4242 │ frc339  │ frc2186 │ 2019vahay_qf2m1_blue │
│ 8   │ frc4242 │ frc339  │ frc2186 │ 2019vahay_qf2m2_blue │
│ 9   │ frc888  │ frc2028 │ frc3455 │ 2019vahay_qf3m1_blue │
│ 10  │ frc888  │ frc2028 │ frc3455 │ 2019vahay_qf3m2_blue │
⋮
│ 170 │ frc1262 │ frc1413 │ frc5546 │ 2019vagle_qm71_blue  │
│ 171 │ frc122  │ frc7429 │ frc6882 │ 2019vagle_qm72_blue  │
│ 172 │ frc1599 │ frc3258 │ frc2998 │ 2019vagle_qm73_blue  │
│ 173 │ frc1598 │ frc346  │ frc1086 │ 2019vagle_qm74_blue  │
│ 174 │ frc1522 │ frc2998 │ frc422  │ 2019vagle_qm8_blue   │
│ 175 │ frc1080 │ frc1598 │ frc539  │ 2019vagle_qm9_blue   │
│ 176 │ frc2106 │ frc1599 │ frc5804 │ 2019vagle_sf1m1_blue │
│ 177 │ frc2106 │ frc1599 │ frc5804 │ 2019vagle_sf1m2_blue │
│ 178 │ frc1610 │ frc384  │ frc3359 │ 2019vagle_sf2m1_blue │
│ 179 │ frc1610 │ frc384  │ frc3359 │ 2019vagle_sf2m2_blue │
│ 180 │ frc1610 │ frc384  │ frc3359 │ 2019vagle_sf2m3_blue │

In [7]:
scoreline(teams, scores) = let stacked = stack(teams, [:team1, :team2, :team3], variable_name=:role, value_name=:team)
    join(scores, stacked, on=:key)
end

scoreline_blue = scoreline(teams_blue, scores_blue)
scoreline_red = scoreline(teams_red, scores_red)

540×62 DataFrame. Omitted printing of 58 columns
│ Row │ adjustPoints │ autoPoints │ bay1          │ bay2          │
│     │ Int64⍰       │ Int64⍰     │ String⍰       │ String⍰       │
├─────┼──────────────┼────────────┼───────────────┼───────────────┤
│ 1   │ 0            │ 15         │ PanelAndCargo │ PanelAndCargo │
│ 2   │ 0            │ 15         │ PanelAndCargo │ PanelAndCargo │
│ 3   │ 0            │ 15         │ PanelAndCargo │ PanelAndCargo │
│ 4   │ 0            │ 15         │ PanelAndCargo │ PanelAndCargo │
│ 5   │ 0            │ 15         │ PanelAndCargo │ PanelAndCargo │
│ 6   │ 0            │ 15         │ PanelAndCargo │ PanelAndCargo │
│ 7   │ 0            │ 15         │ Panel         │ PanelAndCargo │
│ 8   │ 0            │ 15         │ Panel         │ PanelAndCargo │
│ 9   │ 0            │ 15         │ Panel         │ PanelAndCargo │
│ 10  │ 0            │ 15         │ PanelAndCargo │ PanelAndCargo │
⋮
│ 530 │ 0            │ 9          │ PanelAndCargo │ PanelAndCargo │
│ 531 │ 0            │ 9          │ PanelAndCargo │ PanelAndCargo │
│ 532 │ 0            │ 15         │ Panel         │ PanelAndCargo │
│ 533 │ 0            │ 15         │ Panel         │ PanelAndCargo │
│ 534 │ 0            │ 15         │ Panel         │ PanelAndCargo │
│ 535 │ 0            │ 15         │ PanelAndCargo │ PanelAndCargo │
│ 536 │ 0            │ 15         │ PanelAndCargo │ PanelAndCargo │
│ 537 │ 0            │ 15         │ PanelAndCargo │ PanelAndCargo │
│ 538 │ 0            │ 15         │ Panel         │ PanelAndCargo │
│ 539 │ 0            │ 15         │ Panel         │ PanelAndCargo │
│ 540 │ 0            │ 15         │ Panel         │ PanelAndCargo │

In [8]:
numericcols = Lib.numeric_col_names(scoreline_red)
diff_red = convert(Matrix,scoreline_red[:,numericcols]) .- convert(Matrix, scoreline_blue[:,numericcols])
diff_blue = convert(Matrix,scoreline_blue[:,numericcols]) .- convert(Matrix, scoreline_red[:,numericcols])

diffdf = DataFrame(vcat(diff_red, diff_blue), numericcols)
diffdf[:key] = vcat(scoreline_red.key, scoreline_blue.key)
diffdf[:team] = vcat(scoreline_red.team, scoreline_blue.team)

1080-element Array{Union{Missing, String},1}:
 "frc2363"
 "frc612" 
 "frc1731"
 "frc2363"
 "frc612" 
 "frc1731"
 "frc2363"
 "frc612" 
 "frc1731"
 "frc2363"
 "frc612" 
 "frc1731"
 "frc2363"
 ⋮        
 "frc2106"
 "frc1599"
 "frc5804"
 "frc1610"
 "frc384" 
 "frc3359"
 "frc1610"
 "frc384" 
 "frc3359"
 "frc1610"
 "frc384" 
 "frc3359"

In [9]:
win(pointsMargin) = 
    if pointsMargin > 0 
        1.0
    elseif pointsMargin < 0 
        0.0
    else 
        0.5
    end

diffdf[:win] = win.(diffdf.totalPoints)
push!(numericcols, :win)

22-element Array{Symbol,1}:
 :adjustPoints              
 :autoPoints                
 :cargoPoints               
 :completeRocketRankingPoint
 :completedRocketFar        
 :completedRocketNear       
 :foulCount                 
 :foulPoints                
 :habClimbPoints            
 :habDockingRankingPoint    
 :hatchPanelPoints          
 :rp                        
 :sandStormBonusPoints      
 :techFoulCount             
 :teleopPoints              
 :totalPoints               
 :rocketLowPoints           
 :rocketMidPoints           
 :rocketTopPoints           
 :rocketPoints              
 :ownPoints                 
 :win                       

In [10]:
plusminus = by(diffdf, :team, Dict(n => mean for n in numericcols)...)

75×23 DataFrame. Omitted printing of 19 columns
│ Row │ team    │ adjustPoints_mean │ foulPoints_mean │ cargoPoints_mean │
│     │ String⍰ │ Float64           │ Float64         │ Float64          │
├─────┼─────────┼───────────────────┼─────────────────┼──────────────────┤
│ 1   │ frc2363 │ 3.2               │ 0.7             │ 0.9              │
│ 2   │ frc612  │ 3.2               │ 1.05            │ 1.95             │
│ 3   │ frc1731 │ 3.04762           │ 0.857143        │ 1.0              │
│ 4   │ frc4099 │ 0.0               │ 1.1875          │ 3.5625           │
│ 5   │ frc5338 │ 0.0               │ 1.9375          │ 0.9375           │
│ 6   │ frc4505 │ 0.0               │ -1.0            │ 1.3125           │
│ 7   │ frc1418 │ 0.0               │ 0.7             │ 1.8              │
│ 8   │ frc614  │ 0.0               │ 3.75            │ 6.15             │
│ 9   │ frc6543 │ 0.0               │ 0.2             │ 1.2              │
│ 10  │ frc2199 │ 0.0               │ -0.941176       │ 0.0              │
⋮
│ 65  │ frc7330 │ 0.0               │ -1.41667        │ -2.0             │
│ 66  │ frc3136 │ 0.0               │ -1.35714        │ -0.214286        │
│ 67  │ frc2998 │ 0.0               │ 0.4             │ 5.0              │
│ 68  │ frc122  │ 0.0               │ -0.0714286      │ 2.78571          │
│ 69  │ frc1793 │ 0.0               │ 2.0             │ -1.2             │
│ 70  │ frc1080 │ 0.0               │ 0.5             │ 3.5              │
│ 71  │ frc5957 │ 0.0               │ -0.928571       │ -5.78571         │
│ 72  │ frc619  │ 0.0               │ 1.85714         │ -3.64286         │
│ 73  │ frc6334 │ 0.0               │ 2.07143         │ -3.0             │
│ 74  │ frc422  │ 0.0               │ 0.0             │ 5.35714          │
│ 75  │ frc3361 │ 0.0               │ 1.08333         │ -1.5             │

In [11]:
showbest(col) = sort(plusminus, col, rev=true)[:,[:team, col]]
showworst(col) = sort(plusminus, col)[:,[:team, col]]

showbest(:win_mean)

75×2 DataFrame
│ Row │ team    │ win_mean │
│     │ String⍰ │ Float64  │
├─────┼─────────┼──────────┤
│ 1   │ frc346  │ 0.916667 │
│ 2   │ frc612  │ 0.85     │
│ 3   │ frc1262 │ 0.833333 │
│ 4   │ frc2534 │ 0.764706 │
│ 5   │ frc977  │ 0.764706 │
│ 6   │ frc614  │ 0.75     │
│ 7   │ frc1610 │ 0.736842 │
│ 8   │ frc339  │ 0.692308 │
│ 9   │ frc4099 │ 0.6875   │
│ 10  │ frc2363 │ 0.65     │
⋮
│ 65  │ frc1086 │ 0.291667 │
│ 66  │ frc3941 │ 0.272727 │
│ 67  │ frc4464 │ 0.272727 │
│ 68  │ frc5950 │ 0.25     │
│ 69  │ frc7330 │ 0.25     │
│ 70  │ frc3274 │ 0.227273 │
│ 71  │ frc5957 │ 0.214286 │
│ 72  │ frc6021 │ 0.208333 │
│ 73  │ frc620  │ 0.181818 │
│ 74  │ frc2421 │ 0.136364 │
│ 75  │ frc2819 │ 0.136364 │

In [12]:
using CSV
CSV.write("../output/$(KEY)_plusminus.csv", plusminus)

"../output/2019chs_wk1_plusminus.csv"