In [1]:
include("../lib/Lib.jl")
include("../lib/DeepSpace.jl")

Main.DeepSpace

In [2]:
using DataFrames, DataFramesMeta
using CSV
using Statistics

In [3]:
KEY = "2019chs_wk1"
YEAR = "2019"
COLUMN = :teleopSwitchOwnershipSec

:teleopSwitchOwnershipSec

In [4]:
(headers, scores, teams) = Lib.read_stacked(KEY, YEAR)
scores[:color] = repeat(["r", "b"], size(scores,1) >> 1)
teams[:color] = repeat(["r", "b"], size(teams,1) >> 1)

360-element Array{String,1}:
 "r"
 "b"
 "r"
 "b"
 "r"
 "b"
 "r"
 "b"
 "r"
 "b"
 "r"
 "b"
 "r"
 ⋮  
 "r"
 "b"
 "r"
 "b"
 "r"
 "b"
 "r"
 "b"
 "r"
 "b"
 "r"
 "b"

In [5]:
DeepSpace.calculated_columns!(scores)
scores[:ownPoints] = scores.totalPoints .- scores.foulPoints .- (3 .* scores.foulCount) .- (9 * scores.techFoulCount)

360-element Array{Int64,1}:
  62
  82
  72
  71
  66
  65
  52
  54
  62
  35
  59
 -25
  63
   ⋮
  20
  12
  70
  45
  59
  47
  57
  60
  74
  66
  51
  55

In [30]:
scores_train = @linq scores |> where(:level .== "qm")
teams_train = @linq teams |> where(:level .== "qm")

scores_red = @linq scores_train |> where(:color .== "r")
scores_blue = @linq scores_train |> where(:color .== "b")
teams_red = @linq teams_train |> where(:color .== "r") |> select(:team1, :team2, :team3, :key)
teams_blue = @linq teams_train |> where(:color .== "b") |> select(:team1, :team2, :team3, :key)

144×4 DataFrame
│ Row │ team1   │ team2   │ team3   │ key                 │
│     │ String⍰ │ String⍰ │ String⍰ │ String⍰             │
├─────┼─────────┼─────────┼─────────┼─────────────────────┤
│ 1   │ frc620  │ frc339  │ frc5338 │ 2019vahay_qm1_blue  │
│ 2   │ frc2028 │ frc316  │ frc2363 │ 2019vahay_qm10_blue │
│ 3   │ frc3274 │ frc339  │ frc2534 │ 2019vahay_qm11_blue │
│ 4   │ frc888  │ frc2186 │ frc5549 │ 2019vahay_qm12_blue │
│ 5   │ frc611  │ frc612  │ frc6584 │ 2019vahay_qm13_blue │
│ 6   │ frc1123 │ frc620  │ frc4505 │ 2019vahay_qm14_blue │
│ 7   │ frc614  │ frc339  │ frc2421 │ 2019vahay_qm15_blue │
│ 8   │ frc1629 │ frc6504 │ frc6584 │ 2019vahay_qm16_blue │
│ 9   │ frc4464 │ frc3941 │ frc3274 │ 2019vahay_qm17_blue │
│ 10  │ frc5338 │ frc3455 │ frc2186 │ 2019vahay_qm18_blue │
⋮
│ 134 │ frc6189 │ frc5950 │ frc1080 │ 2019vagle_qm67_blue │
│ 135 │ frc1908 │ frc7429 │ frc3359 │ 2019vagle_qm68_blue │
│ 136 │ frc4286 │ frc5804 │ frc619  │ 2019vagle_qm69_blue │
│ 137 │ frc540  │ frc122  │ frc5950 │ 2019vagle_qm7_blue  │
│ 138 │ frc617  │ frc1610 │ frc6189 │ 2019vagle_qm70_blue │
│ 139 │ frc1262 │ frc1413 │ frc5546 │ 2019vagle_qm71_blue │
│ 140 │ frc122  │ frc7429 │ frc6882 │ 2019vagle_qm72_blue │
│ 141 │ frc1599 │ frc3258 │ frc2998 │ 2019vagle_qm73_blue │
│ 142 │ frc1598 │ frc346  │ frc1086 │ 2019vagle_qm74_blue │
│ 143 │ frc1522 │ frc2998 │ frc422  │ 2019vagle_qm8_blue  │
│ 144 │ frc1080 │ frc1598 │ frc539  │ 2019vagle_qm9_blue  │

In [31]:
scoreline(teams, scores) = let stacked = stack(teams, [:team1, :team2, :team3], variable_name=:role, value_name=:team)
    join(scores, stacked, on=:key)
end

scoreline_blue = scoreline(teams_blue, scores_blue)
scoreline_red = scoreline(teams_red, scores_red)

432×62 DataFrame. Omitted printing of 57 columns
│ Row │ adjustPoints │ autoPoints │ bay1    │ bay2          │ bay3          │
│     │ Int64⍰       │ Int64⍰     │ String⍰ │ String⍰       │ String⍰       │
├─────┼──────────────┼────────────┼─────────┼───────────────┼───────────────┤
│ 1   │ 0            │ 9          │ Panel   │ Panel         │ PanelAndCargo │
│ 2   │ 0            │ 9          │ Panel   │ Panel         │ PanelAndCargo │
│ 3   │ 0            │ 9          │ Panel   │ Panel         │ PanelAndCargo │
│ 4   │ 0            │ 6          │ None    │ Panel         │ Panel         │
│ 5   │ 0            │ 6          │ None    │ Panel         │ Panel         │
│ 6   │ 0            │ 6          │ None    │ Panel         │ Panel         │
│ 7   │ 0            │ 3          │ None    │ None          │ None          │
│ 8   │ 0            │ 3          │ None    │ None          │ None          │
│ 9   │ 0            │ 3          │ None    │ None          │ None          │
│ 10  │ 0            │ 6          │ None    │ PanelAndCargo │ PanelAndCargo │
⋮
│ 422 │ 0            │ 12         │ Panel   │ Panel         │ PanelAndCargo │
│ 423 │ 0            │ 12         │ Panel   │ Panel         │ PanelAndCargo │
│ 424 │ 0            │ 15         │ Panel   │ Panel         │ PanelAndCargo │
│ 425 │ 0            │ 15         │ Panel   │ Panel         │ PanelAndCargo │
│ 426 │ 0            │ 15         │ Panel   │ Panel         │ PanelAndCargo │
│ 427 │ 0            │ 12         │ None    │ None          │ None          │
│ 428 │ 0            │ 12         │ None    │ None          │ None          │
│ 429 │ 0            │ 12         │ None    │ None          │ None          │
│ 430 │ 0            │ 6          │ Panel   │ Panel         │ Panel         │
│ 431 │ 0            │ 6          │ Panel   │ Panel         │ Panel         │
│ 432 │ 0            │ 6          │ Panel   │ Panel         │ Panel         │

In [32]:
numericcols = Lib.numeric_col_names(scoreline_red)
diff_red = convert(Matrix,scoreline_red[:,numericcols]) .- convert(Matrix, scoreline_blue[:,numericcols])
diff_blue = convert(Matrix,scoreline_blue[:,numericcols]) .- convert(Matrix, scoreline_red[:,numericcols])

diffdf = DataFrame(vcat(diff_red, diff_blue), numericcols)
diffdf[:key] = vcat(scoreline_red.key, scoreline_blue.key)
diffdf[:team] = vcat(scoreline_red.team, scoreline_blue.team)

864-element Array{Union{Missing, String},1}:
 "frc4505"
 "frc2988"
 "frc3941"
 "frc2421"
 "frc3941"
 "frc1719"
 "frc623" 
 "frc1418"
 "frc4464"
 "frc2961"
 "frc5338"
 "frc4242"
 "frc6543"
 ⋮        
 "frc1599"
 "frc3258"
 "frc2998"
 "frc1598"
 "frc346" 
 "frc1086"
 "frc1522"
 "frc2998"
 "frc422" 
 "frc1080"
 "frc1598"
 "frc539" 

In [33]:
win(pointsMargin) = 
    if pointsMargin > 0 
        1.0
    elseif pointsMargin < 0 
        0.0
    else 
        0.5
    end

diffdf[:win] = win.(diffdf.totalPoints)
push!(numericcols, :win)

22-element Array{Symbol,1}:
 :adjustPoints              
 :autoPoints                
 :cargoPoints               
 :completeRocketRankingPoint
 :completedRocketFar        
 :completedRocketNear       
 :foulCount                 
 :foulPoints                
 :habClimbPoints            
 :habDockingRankingPoint    
 :hatchPanelPoints          
 :rp                        
 :sandStormBonusPoints      
 :techFoulCount             
 :teleopPoints              
 :totalPoints               
 :rocketLowPoints           
 :rocketMidPoints           
 :rocketTopPoints           
 :rocketPoints              
 :ownPoints                 
 :win                       

In [34]:
plusminus = by(diffdf, :team, Dict(n => mean for n in numericcols)...)

75×23 DataFrame. Omitted printing of 19 columns
│ Row │ team    │ adjustPoints_mean │ foulPoints_mean │ cargoPoints_mean │
│     │ String⍰ │ Float64           │ Float64         │ Float64          │
├─────┼─────────┼───────────────────┼─────────────────┼──────────────────┤
│ 1   │ frc4505 │ 0.0               │ -3.45455        │ 0.0              │
│ 2   │ frc2988 │ 0.0               │ -0.818182       │ -0.545455        │
│ 3   │ frc3941 │ 0.0               │ -2.81818        │ 1.09091          │
│ 4   │ frc2421 │ 0.0               │ -0.363636       │ -2.72727         │
│ 5   │ frc1719 │ 0.0               │ 2.81818         │ -0.545455        │
│ 6   │ frc623  │ 0.0               │ -0.272727       │ -1.09091         │
│ 7   │ frc1418 │ 0.0               │ -0.909091       │ 1.63636          │
│ 8   │ frc4464 │ 0.0               │ -1.36364        │ -4.90909         │
│ 9   │ frc2961 │ 0.0               │ 0.363636        │ -3.54545         │
│ 10  │ frc5338 │ 0.0               │ 0.818182        │ -0.545455        │
⋮
│ 65  │ frc2106 │ 0.0               │ 1.08333         │ -6.0             │
│ 66  │ frc1599 │ 0.0               │ -1.25           │ -0.75            │
│ 67  │ frc1793 │ 0.0               │ 2.0             │ -2.25            │
│ 68  │ frc1080 │ 0.0               │ 0.5             │ 3.5              │
│ 69  │ frc6882 │ 0.0               │ -1.08333        │ 0.75             │
│ 70  │ frc5957 │ 0.0               │ -1.08333        │ -6.0             │
│ 71  │ frc619  │ 0.0               │ 2.16667         │ -3.5             │
│ 72  │ frc6334 │ 0.0               │ 1.91667         │ -3.25            │
│ 73  │ frc422  │ 0.0               │ -0.5            │ 6.5              │
│ 74  │ frc3361 │ 0.0               │ 1.08333         │ -1.5             │
│ 75  │ frc539  │ 0.0               │ 1.41667         │ -3.75            │

In [35]:
showbest(col) = sort(plusminus, col, rev=true)[:,[:team, col]]
showworst(col) = sort(plusminus, col)[:,[:team, col]]

showbest(:win_mean)

75×2 DataFrame
│ Row │ team    │ win_mean │
│     │ String⍰ │ Float64  │
├─────┼─────────┼──────────┤
│ 1   │ frc612  │ 1.0      │
│ 2   │ frc2534 │ 0.909091 │
│ 3   │ frc614  │ 0.909091 │
│ 4   │ frc346  │ 0.875    │
│ 5   │ frc1610 │ 0.833333 │
│ 6   │ frc977  │ 0.833333 │
│ 7   │ frc339  │ 0.818182 │
│ 8   │ frc1262 │ 0.75     │
│ 9   │ frc4099 │ 0.727273 │
│ 10  │ frc2998 │ 0.708333 │
⋮
│ 65  │ frc4464 │ 0.272727 │
│ 66  │ frc6543 │ 0.272727 │
│ 67  │ frc5950 │ 0.25     │
│ 68  │ frc7330 │ 0.25     │
│ 69  │ frc3359 │ 0.25     │
│ 70  │ frc5957 │ 0.25     │
│ 71  │ frc3274 │ 0.227273 │
│ 72  │ frc6021 │ 0.208333 │
│ 73  │ frc620  │ 0.181818 │
│ 74  │ frc2421 │ 0.136364 │
│ 75  │ frc2819 │ 0.136364 │

In [36]:
using CSV
CSV.write("../output/$(KEY)_plusminus.csv", plusminus)

"../output/2019chs_wk1_plusminus.csv"